production:
  host: ds029177.mongolab.com
  port: 29177
  username: heroku_app2036400
  password: bscun6son1c7q539jasfq3r85n
  database: heroku_app2036400
  raise_not_found_error: false
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019