development:
  host: localhost
  database: project_limelight_development

test:
  host: localhost
  database: project_limelight_test

# set these environment variables on your prod server
production:
#  host: <%= ENV['MONGOID_HOST'] %>
#  port: <%= ENV['MONGOID_PORT'] %>
#  username: <%= ENV['MONGOID_USERNAME'] %>
#  password: <%= ENV['MONGOID_PASSWORD'] %>
#  database: <%= ENV['MONGOID_DATABASE'] %>
  host: dbh35.mongolab.com
  port: 27357
  username: project_limelight
  password: pUtJyt8HCHY8
  database: project_limelight
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
