defaults: &defaults
raise_not_found_error: false

development:
  host: localhost
  database: project_limelight_development
  raise_not_found_error: false
  autocreate_indexes: true

test:
  host: localhost
  database: project_limelight_test

# set these environment variables on your prod server
production:
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019