production:
  host: ds029177.mongolab.com
  port: 29177
  username: heroku_app2036400
  password: bscun6son1c7q539jasfq3r85n
  database: heroku_app2036400
  raise_not_found_error: false

development:
  host: localhost
  database: limelight_development
  raise_not_found_error: false
  autocreate_indexes: true

test:
  host: localhost
  database: limelight_test
  raise_not_found_error: false
  autocreate_indexes: true

staging:
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>
  raise_not_found_error: false