recalculate_popularity:
  every: 10m
  class: RecalculatePopularity
  args:
  description: "This job recalculates popularity scores"

recalculate_averages:
  every: 1h
  class: RecalculateAverages
  args:
  description: "This job recalculates popularity averages for each root type"

recalculate_clout:
  every: 45m
  class: RecalculateClout
  args:
  description: "This job recalculates user clout"

#weekly_email:
#  cron: "0 15 * * fri"
#  class: WeeklyEmail
#  args:
#  description: "This job sends users a periodic content-you-might-like email"

daily_notifications:
  cron: "0 14 * * *"
  class: SendDailyUserNotifications
  args:
  description: "This job sends users a daily email with their new notifications"