development: &defaults
  connection:
    :access_key_id: 'AKIAIQDM2Y5J44SJILXA'
    :secret_access_key: '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'
    :use_ssl: true
    # :persistent: true
  cloudfront_id: "EOKKI5GMUVBB9"
  image_bucket: "development.img.p-li.me"
  image_prefix: "http://development.img.p-li.me"
#  image_bucket: "img.p-li.me"
#  image_prefix: "http://img.p-li.me"
  max_file_size: 10485760
  acl: public-read

test:
  <<: *defaults

staging:
  <<: *defaults
  cloudfront_id: "EGT0XWGY6ELAY"
  image_bucket: "staging.img.p-li.me"
  image_prefix: "http://staging.img.p-li.me"

production:
  <<: *defaults
  # prefix is optional. This is where you would put your CloudFront Domain
  # Name or your CloudFront CNAME if you have one configured.
  cloudfront_id: "E2P9H5V4PQJQ0"
  image_bucket: "img.p-li.me"
  image_prefix: "http://img.p-li.me"